Repository Leagify/JMR-stats, pull requests merged in 2020-10, with the labels that each got.

#15 Issue #12 - Rename 2019 -> S01, 2020 -> S02
  MarbulaOne/S01/S01-finishingRacePositions.csv
  MarbulaOne/S01/S01-points.csv
  MarbulaOne/S01/S01-qualifyingPositions.csv
  MarbulaOne/S01/overallStandings.csv
  MarbulaOne/S02/overallStandings.csv
Labels: hacktoberfest

#16 Adds events 7 to 11 to Marble League 2020
  MarbleLeague/2020/2020-finalStandings.csv
Labels: enhancement, hacktoberfest

#17 Adds results through event 16 - Closes #11
  MarbleLeague/2020/2020-finalStandings.csv
Labels: enhancement, hacktoberfest

#18 Creates Marble Rally directory and adds Race 1-2 - Closes #14
  MarbleRally/2020/2020-finishingRacePositions.csv
  MarbleRally/2020/2020-points.csv
  MarbleRally/2020/2020-startingPositions.csv
  MarbleRally/2020/NamesToHashTags.csv
  MarbleRally/2020/overallStandings.csv
  MarbulaOne/S01/S01-finishingRacePositions.csv
  MarbulaOne/S01/S01-qualifyingPositions.csv
Labels: hacktoberfest

#23 added NamesToHashTags and overallStandings
  MarbleRally/2016/2016-finishingRacePositions.csv
  MarbleRally/2016/2016-points.csv
  MarbleRally/2016/2016-startingPositions.csv
  MarbleRally/2016/NamesToHashTags.csv
  MarbleRally/2016/overallStandings.csv
Labels: hacktoberfest, hacktoberfest-accepted

#27 Create 2016-cumulative-points.csv
  MarbleRally/2016/2016-cumulative-points.csv
Labels: hacktoberfest, hacktoberfest-accepted

#26 Marble Rally - 2016 updates, 2020 points by race
  MarbleRally/2016/overallStandings.csv
  MarbleRally/2020/2020-cumulative-points.csv
  MarbleRally/2020/2020-points-by-race.csv
Labels: hacktoberfest, hacktoberfest-accepted

#28 Updated stats for Marbula E
  MarbulaOne/S02/S02-finishingRacePositions.csv
  MarbulaOne/S02/S02-points.csv
  MarbulaOne/S02/S02-qualifyingPositions.csv
Labels: hacktoberfest, hacktoberfest-accepted

#29 Fixes location of Formula E data, adds additional points csv files.
  MarbulaE/2020/2020-cumulative-points.csv
  MarbulaE/2020/2020-finishingRacePositions.csv
  MarbulaE/2020/2020-points-by-race.csv
  MarbulaE/2020/2020-qualifyingPositions.csv
  MarbulaOne/S01/S01-cumulative-points.csv
  MarbulaOne/S01/S01-points-by-race.csv
Labels: hacktoberfest, hacktoberfest-accepted

#31 Update 2020-cumulative-points.csv
  MarbulaE/2020/2020-cumulative-points.csv
Labels: hacktoberfest, hacktoberfest-accepted

#32 Add Race 3 and Race 4 info for Marble Rally 2020
  MarbleRally/2020/2020-cumulative-points.csv
  MarbleRally/2020/2020-finishingRacePositions.csv
  MarbleRally/2020/2020-points-by-race.csv
  MarbleRally/2020/2020-startingPositions.csv
Labels: hacktoberfest, hacktoberfest-accepted

#34 Adds race 5 results - closes #33
  MarbleRally/2020/2020-cumulative-points.csv
  MarbleRally/2020/2020-finishingRacePositions.csv
  MarbleRally/2020/2020-points-by-race.csv
  MarbleRally/2020/2020-startingPositions.csv
  MarbleRally/2020/overallStandings.csv
Labels: hacktoberfest, hacktoberfest-accepted, marble-rally

#36 Adds DNF results from race 1-4 - Closes #35
  MarbleRally/2020/overallStandings.csv
Labels: hacktoberfest, hacktoberfest-accepted, marble-rally

#37 adds Marbula One S2 CSVs leading up to new season
  MarbulaOne/S02/S02-cumulative-points.csv
  MarbulaOne/S02/S02-finishingRacePositions.csv
  MarbulaOne/S02/S02-points-by-race.csv
  MarbulaOne/S02/S02-qualifyingPositions.csv
Labels: hacktoberfest, hacktoberfest-accepted, marbula-one

#40 Marble Rally Race 6
  MarbleRally/2020/2020-cumulative-points.csv
  MarbleRally/2020/2020-finishingRacePositions.csv
  MarbleRally/2020/2020-points-by-race.csv
  MarbleRally/2020/2020-startingPositions.csv
  MarbleRally/2020/overallStandings.csv
Labels: hacktoberfest, marble-rally

#41 Adds 2017 Marble Rally - Closes #21
  MarbleRally/2016/2016-overallStandings.csv
  MarbleRally/2017/2017-cumulative-points.csv
  MarbleRally/2017/2017-finishingRacePositions.csv
  MarbleRally/2017/2017-overallStandings.csv
  MarbleRally/2017/2017-points-by-race.csv
  MarbleRally/2017/2017-startingPositions.csv
  MarbleRally/2017/NamesToHashTags.csv
Labels: hacktoberfest, marble-rally

#44 adds 2017 starting positions - Closes #43
  MarbleRally/2017/2017-startingPositions.csv
Labels: hacktoberfest, marble-rally

#45 Marbula One S1-changes to points by race
  MarbulaOne/S01/S01-points-by-race.csv
Labels: hacktoberfest, marbula-one

#46 removes trailing comma
  MarbulaOne/S01/S01-cumulative-points.csv
  MarbulaOne/S01/S01-finishingRacePositions.csv
  MarbulaOne/S01/S01-qualifyingPositions.csv
Labels: hacktoberfest, marbula-one
